# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 18:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='ERP_User',
        ),
    ]
