# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_erp_user_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='erp_user',
            name='user',
        ),
    ]
