# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0006_erp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='erp_user',
            name='email',
            field=models.CharField(default='n/a', max_length=50),
            preserve_default=False,
        ),
    ]
