# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0008_auto_20160707_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebAppUserSites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=254, unique=True)),
                ('site_name', models.CharField(max_length=254, unique=True)),
                ('db_name', models.CharField(max_length=254, unique=True)),
            ],
            options={
                'db_table': 'web_app_user_sites',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='User_Sites',
        ),
    ]
