# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0009_auto_20160707_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Sites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=254, unique=True)),
                ('site_name', models.CharField(max_length=254, unique=True)),
                ('db_name', models.CharField(max_length=254, unique=True)),
            ],
        ),
    ]
