# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0010_user_sites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_sites',
            name='username',
        ),
        migrations.AddField(
            model_name='user_sites',
            name='user',
            field=models.ForeignKey(default='Administrator', on_delete=django.db.models.deletion.DO_NOTHING, to='web_app.AuthUser'),
        ),
    ]
