# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0011_auto_20160707_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_sites',
            name='user',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.DO_NOTHING, to='web_app.AuthUser'),
        ),
    ]
