# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0012_auto_20160707_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_sites',
            name='user',
        ),
        migrations.AddField(
            model_name='user_sites',
            name='username',
            field=models.CharField(default='Administrator', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
